import { LanguageInterface } from 'lang/LanguageInterface';
import { ChromaticChord } from '../chords/chromatic/ChromaticChord';
import { DiatonicAltChord } from '../chords/diatonicalt/DiatonicAltChord';
import { Chromatic } from '../degrees/Chromatic';
import { DiatonicAlt } from '../degrees/DiatonicAlt';
import { Language } from '../lang/Language';
import { DiatonicAltPattern } from '../patterns/DiatonicAltPattern';
import { Scale } from '../tonality/Scale';
import { Tonality } from '../tonality/Tonality';
import { ConcertPitch } from '../tuning/ConcertPitch';
import { Temperament } from '../tuning/Temperament';
import { Tuning } from '../tuning/Tuning';
import { Settings } from './Settings';
import { SettingsInterface } from './SettingsInterface';

export const DefaultSettings: SettingsInterface = {
    default: {
        get chromatic(): Chromatic { return Chromatic.C },
        get diatonicAlt(): DiatonicAlt { return DiatonicAlt.C },
        get scale(): Scale { return Scale.MAJOR },
        get tonality(): Tonality { return Tonality.C },
        get chromaticChord(): ChromaticChord { return ChromaticChord.C },
        get chord(): DiatonicAltChord { return DiatonicAltChord.C },
        get pattern(): DiatonicAltPattern { return DiatonicAltPattern.TRIAD_MAJOR },
        get temperament(): Temperament { return Temperament.ET12 },
        get tuning(): Tuning { return Tuning.EQUAL_440 },
        get concertPitch(): ConcertPitch { return ConcertPitch.A440 },
    },
    get baseLang(): LanguageInterface { return Language.ENG },
    lang: {
        id: "BASE",
        diatonic: {
            get C(): string { return Language.CUSTOM.diatonic.C || Settings.baseLang.diatonic.C },
            get D(): string { return Language.CUSTOM.diatonic.D || Settings.baseLang.diatonic.D },
            get E(): string { return Language.CUSTOM.diatonic.E || Settings.baseLang.diatonic.E },
            get F(): string { return Language.CUSTOM.diatonic.F || Settings.baseLang.diatonic.F },
            get G(): string { return Language.CUSTOM.diatonic.G || Settings.baseLang.diatonic.G },
            get A(): string { return Language.CUSTOM.diatonic.A || Settings.baseLang.diatonic.A },
            get B(): string { return Language.CUSTOM.diatonic.B || Settings.baseLang.diatonic.B },
        },
        scales: {
            get MAJOR(): string { return Language.CUSTOM.scales.MAJOR || Settings.baseLang.scales.MAJOR },
            get MINOR(): string { return Language.CUSTOM.scales.MINOR || Settings.baseLang.scales.MINOR },
            get DORIAN(): string { return Language.CUSTOM.scales.DORIAN || Settings.baseLang.scales.DORIAN },
            get PHRYGIAN(): string { return Language.CUSTOM.scales.PHRYGIAN || Settings.baseLang.scales.PHRYGIAN },
            get LYDIAN(): string { return Language.CUSTOM.scales.LYDIAN || Settings.baseLang.scales.LYDIAN },
            get MIXOLYDIAN(): string { return Language.CUSTOM.scales.MIXOLYDIAN || Settings.baseLang.scales.MIXOLYDIAN },
            get LOCRIAN(): string { return Language.CUSTOM.scales.LOCRIAN || Settings.baseLang.scales.LOCRIAN },

            get HARMONIC_MINOR(): string { return Language.CUSTOM.scales.HARMONIC_MINOR || Settings.baseLang.scales.HARMONIC_MINOR },
            get LOCRIAN_a6(): string { return Language.CUSTOM.scales.LOCRIAN_a6 || Settings.baseLang.scales.LOCRIAN_a6 },
            get IONIAN_a5(): string { return Language.CUSTOM.scales.IONIAN_a5 || Settings.baseLang.scales.IONIAN_a5 },
            get DORIAN_a4(): string { return Language.CUSTOM.scales.DORIAN_a4 || Settings.baseLang.scales.DORIAN_a4 },
            get MIXOLYDIAN_b9_b13(): string { return Language.CUSTOM.scales.MIXOLYDIAN_b9_b13 || Settings.baseLang.scales.MIXOLYDIAN_b9_b13 },
            get LYDIAN_a2(): string { return Language.CUSTOM.scales.LYDIAN_a2 || Settings.baseLang.scales.LYDIAN_a2 },
            get SUPERLOCRIAN_bb7(): string { return Language.CUSTOM.scales.SUPERLOCRIAN_bb7 || Settings.baseLang.scales.SUPERLOCRIAN_bb7 },

            get HARMONIC_MAJOR(): string { return Language.CUSTOM.scales.HARMONIC_MAJOR || Settings.baseLang.scales.HARMONIC_MAJOR },
            get DORIAN_b5(): string { return Language.CUSTOM.scales.DORIAN_b5 || Settings.baseLang.scales.DORIAN_b5 },
            get PHRYGIAN_b4(): string { return Language.CUSTOM.scales.PHRYGIAN_b4 || Settings.baseLang.scales.PHRYGIAN_b4 },
            get LYDIAN_b3(): string { return Language.CUSTOM.scales.LYDIAN_b3 || Settings.baseLang.scales.LYDIAN_b3 },
            get MIXOLYDIAN_b2(): string { return Language.CUSTOM.scales.MIXOLYDIAN_b2 || Settings.baseLang.scales.MIXOLYDIAN_b2 },
            get AEOLIAN_b1(): string { return Language.CUSTOM.scales.AEOLIAN_b1 || Settings.baseLang.scales.AEOLIAN_b1 },
            get LOCRIAN_bb7(): string { return Language.CUSTOM.scales.LOCRIAN_bb7 || Settings.baseLang.scales.LOCRIAN_bb7 },

            get MELODIC_MINOR(): string { return Language.CUSTOM.scales.MELODIC_MINOR || Settings.baseLang.scales.MELODIC_MINOR },
            get DORIAN_b2(): string { return Language.CUSTOM.scales.DORIAN_b2 || Settings.baseLang.scales.DORIAN_b2 },
            get LYDIAN_a5(): string { return Language.CUSTOM.scales.LYDIAN_a5 || Settings.baseLang.scales.LYDIAN_a5 },
            get LYDIAN_b7(): string { return Language.CUSTOM.scales.LYDIAN_b7 || Settings.baseLang.scales.LYDIAN_b7 },
            get MIXOLYDIAN_b13(): string { return Language.CUSTOM.scales.MIXOLYDIAN_b13 || Settings.baseLang.scales.MIXOLYDIAN_b13 },
            get LOCRIAN_a2(): string { return Language.CUSTOM.scales.LOCRIAN_a2 || Settings.baseLang.scales.LOCRIAN_a2 },
            get SUPERLOCRIAN(): string { return Language.CUSTOM.scales.SUPERLOCRIAN || Settings.baseLang.scales.SUPERLOCRIAN },

            get DOUBLE_HARMONIC(): string { return Language.CUSTOM.scales.DOUBLE_HARMONIC || Settings.baseLang.scales.DOUBLE_HARMONIC },
            get LYDIAN_a2_a6(): string { return Language.CUSTOM.scales.LYDIAN_a2_a6 || Settings.baseLang.scales.LYDIAN_a2_a6 },
            get ULTRAPHRYGIAN(): string { return Language.CUSTOM.scales.ULTRAPHRYGIAN || Settings.baseLang.scales.ULTRAPHRYGIAN },
            get HUNGARIAN_MINOR(): string { return Language.CUSTOM.scales.HUNGARIAN_MINOR || Settings.baseLang.scales.HUNGARIAN_MINOR },
            get ORIENTAL(): string { return Language.CUSTOM.scales.ORIENTAL || Settings.baseLang.scales.ORIENTAL },
            get IONIAN_AUGMENTED_a2(): string { return Language.CUSTOM.scales.IONIAN_AUGMENTED_a2 || Settings.baseLang.scales.IONIAN_AUGMENTED_a2 },
            get LOCRIAN_bb3_bb7(): string { return Language.CUSTOM.scales.LOCRIAN_bb3_bb7 || Settings.baseLang.scales.LOCRIAN_bb3_bb7 },

            get NEAPOLITAN_MINOR(): string { return Language.CUSTOM.scales.NEAPOLITAN_MINOR || Settings.baseLang.scales.NEAPOLITAN_MINOR },
            get NEAPOLITAN_MAJOR(): string { return Language.CUSTOM.scales.NEAPOLITAN_MAJOR || Settings.baseLang.scales.NEAPOLITAN_MAJOR },

            // 6
            get BLUES_b5(): string { return Language.CUSTOM.scales.BLUES_b5 || Settings.baseLang.scales.BLUES_b5 },
            get BLUES_a4(): string { return Language.CUSTOM.scales.BLUES_a4 || Settings.baseLang.scales.BLUES_a4 },

            get WHOLE_TONE(): string { return Language.CUSTOM.scales.WHOLE_TONE || Settings.baseLang.scales.WHOLE_TONE },

            // 5
            get PENTATONIC_MINOR(): string { return Language.CUSTOM.scales.PENTATONIC_MINOR || Settings.baseLang.scales.PENTATONIC_MINOR },
            get PENTATONIC(): string { return Language.CUSTOM.scales.PENTATONIC || Settings.baseLang.scales.PENTATONIC },
            get EGYPCIAN(): string { return Language.CUSTOM.scales.EGYPCIAN || Settings.baseLang.scales.EGYPCIAN },
            get BLUES_MINOR(): string { return Language.CUSTOM.scales.BLUES_MINOR || Settings.baseLang.scales.BLUES_MINOR },
            get BLUES_MAJOR(): string { return Language.CUSTOM.scales.BLUES_MAJOR || Settings.baseLang.scales.BLUES_MAJOR },

            // 12
            get CHROMATIC(): string { return Language.CUSTOM.scales.CHROMATIC || Settings.baseLang.scales.CHROMATIC },

            get AUGMENTED_TRIAD(): string { return Language.CUSTOM.scales.AUGMENTED_TRIAD || Settings.baseLang.scales.AUGMENTED_TRIAD },
            get DIMINISHED_7th(): string { return Language.CUSTOM.scales.DIMINISHED_7th || Settings.baseLang.scales.DIMINISHED_7th },
            get MESSIAEN_V_TRUNCATED(): string { return Language.CUSTOM.scales.MESSIAEN_V_TRUNCATED || Settings.baseLang.scales.MESSIAEN_V },
            get DOM7b5(): string { return Language.CUSTOM.scales.DOM7b5 || Settings.baseLang.scales.DOM7b5 },
            get MESSIAEN_INV_III_V_TRUNCATED_n2(): string { return Language.CUSTOM.scales.MESSIAEN_INV_III_V_TRUNCATED_n2 || Settings.baseLang.scales.MESSIAEN_INV_III_V_TRUNCATED_n2 },
            get HALF_DIMINISHED(): string { return Language.CUSTOM.scales.HALF_DIMINISHED || Settings.baseLang.scales.HALF_DIMINISHED },
            get MESSIAEN_V(): string { return Language.CUSTOM.scales.MESSIAEN_V || Settings.baseLang.scales.MESSIAEN_V },
            get RAGA_INDRUPRIYA_INDIA(): string { return Language.CUSTOM.scales.RAGA_INDRUPRIYA_INDIA || Settings.baseLang.scales.RAGA_INDRUPRIYA_INDIA },
            get MESSIAEN_II_TRUNCATED_n3(): string { return Language.CUSTOM.scales.MESSIAEN_II_TRUNCATED_n3 || Settings.baseLang.scales.MESSIAEN_II_TRUNCATED_n3 },
            get MESSIAEN_III_INV(): string { return Language.CUSTOM.scales.MESSIAEN_III_INV || Settings.baseLang.scales.MESSIAEN_III_INV },
            get MESSIAEN_IV(): string { return Language.CUSTOM.scales.MESSIAEN_IV || Settings.baseLang.scales.MESSIAEN_IV },
            get MESSIAEN_VI(): string { return Language.CUSTOM.scales.MESSIAEN_VI || Settings.baseLang.scales.MESSIAEN_VI },
            get MESSIAEN_VII(): string { return Language.CUSTOM.scales.MESSIAEN_VII || Settings.baseLang.scales.MESSIAEN_VII },

            get BEBOP_MAJOR(): string { return Language.CUSTOM.scales.BEBOP_MAJOR || Settings.baseLang.scales.BEBOP_MAJOR },
        },
        patterns: {
            get TRIAD_MAJOR(): string { return Language.CUSTOM.patterns.TRIAD_MAJOR || Settings.baseLang.patterns.TRIAD_MAJOR },
            get TRIAD_MINOR(): string { return Language.CUSTOM.patterns.TRIAD_MINOR || Settings.baseLang.patterns.TRIAD_MINOR },
            get TRIAD_AUGMENTED(): string { return Language.CUSTOM.patterns.TRIAD_AUGMENTED || Settings.baseLang.patterns.TRIAD_AUGMENTED },
            get TRIAD_DIMINISHED(): string { return Language.CUSTOM.patterns.TRIAD_DIMINISHED || Settings.baseLang.patterns.TRIAD_DIMINISHED },
            get TRIAD_SUS4(): string { return Language.CUSTOM.patterns.TRIAD_SUS4 || Settings.baseLang.patterns.TRIAD_SUS4 },
            get TRIAD_SUS2(): string { return Language.CUSTOM.patterns.TRIAD_SUS2 || Settings.baseLang.patterns.TRIAD_SUS2 },
            get TRIAD_QUARTAL(): string { return Language.CUSTOM.patterns.TRIAD_QUARTAL || Settings.baseLang.patterns.TRIAD_QUARTAL },
            get ELEVENTH(): string { return Language.CUSTOM.patterns.ELEVENTH || Settings.baseLang.patterns.ELEVENTH },
            get ELEVENTH_MAJ11(): string { return Language.CUSTOM.patterns.ELEVENTH_MAJ11 || Settings.baseLang.patterns.ELEVENTH_MAJ11 },
            get ELEVENTH_MINOR_MAJ11(): string { return Language.CUSTOM.patterns.ELEVENTH_MINOR_MAJ11 || Settings.baseLang.patterns.ELEVENTH_MINOR_MAJ11 },
            get ELEVENTH_a9(): string { return Language.CUSTOM.patterns.ELEVENTH_a9 || Settings.baseLang.patterns.ELEVENTH_a9 },
            get ELEVENTH_b9(): string { return Language.CUSTOM.patterns.ELEVENTH_b9 || Settings.baseLang.patterns.ELEVENTH_b9 },
            get NINTH(): string { return Language.CUSTOM.patterns.NINTH || Settings.baseLang.patterns.NINTH },
            get NINTH_ADD6(): string { return Language.CUSTOM.patterns.NINTH_ADD6 || Settings.baseLang.patterns.NINTH_ADD6 },
            get NINTH_MAJ9(): string { return Language.CUSTOM.patterns.NINTH_MAJ9 || Settings.baseLang.patterns.NINTH_MAJ9 },
            get NINTH_MAJ9_a11(): string { return Language.CUSTOM.patterns.NINTH_MAJ9_a11 || Settings.baseLang.patterns.NINTH_MAJ9_a11 },
            get NINTH_MINOR(): string { return Language.CUSTOM.patterns.NINTH_MINOR || Settings.baseLang.patterns.NINTH_MINOR },
            get NINTH_MINOR_MAJ9(): string { return Language.CUSTOM.patterns.NINTH_MINOR_MAJ9 || Settings.baseLang.patterns.NINTH_MINOR_MAJ9 },
            get NINTH_SUS4(): string { return Language.CUSTOM.patterns.NINTH_SUS4 || Settings.baseLang.patterns.NINTH_SUS4 },
            get NINTH_a11(): string { return Language.CUSTOM.patterns.NINTH_a11 || Settings.baseLang.patterns.NINTH_a11 },
            get NINTH_a5(): string { return Language.CUSTOM.patterns.NINTH_a5 || Settings.baseLang.patterns.NINTH_a5 },
            get NINTH_b5(): string { return Language.CUSTOM.patterns.NINTH_b5 || Settings.baseLang.patterns.NINTH_b5 },
            get POWER_CHORD(): string { return Language.CUSTOM.patterns.POWER_CHORD || Settings.baseLang.patterns.POWER_CHORD },
            get SEVENTH(): string { return Language.CUSTOM.patterns.SEVENTH || Settings.baseLang.patterns.SEVENTH },
            get SEVENTH_ADD11(): string { return Language.CUSTOM.patterns.SEVENTH_ADD11 || Settings.baseLang.patterns.SEVENTH_ADD11 },
            get SEVENTH_ADD13(): string { return Language.CUSTOM.patterns.SEVENTH_ADD13 || Settings.baseLang.patterns.SEVENTH_ADD13 },
            get SEVENTH_MAJ7(): string { return Language.CUSTOM.patterns.SEVENTH_MAJ7 || Settings.baseLang.patterns.SEVENTH_MAJ7 },
            get SEVENTH_MINOR(): string { return Language.CUSTOM.patterns.SEVENTH_MINOR || Settings.baseLang.patterns.SEVENTH_MINOR },
            get SEVENTH_MINOR_MAJ7(): string { return Language.CUSTOM.patterns.SEVENTH_MINOR_MAJ7 || Settings.baseLang.patterns.SEVENTH_MINOR_MAJ7 },
            get SEVENTH_MINOR_a5(): string { return Language.CUSTOM.patterns.SEVENTH_MINOR_a5 || Settings.baseLang.patterns.SEVENTH_MINOR_a5 },
            get SEVENTH_MINOR_b5(): string { return Language.CUSTOM.patterns.SEVENTH_MINOR_b5 || Settings.baseLang.patterns.SEVENTH_MINOR_b5 },
            get SEVENTH_MINOR_b9(): string { return Language.CUSTOM.patterns.SEVENTH_MINOR_b9 || Settings.baseLang.patterns.SEVENTH_MINOR_b9 },
            get SEVENTH_SUS4(): string { return Language.CUSTOM.patterns.SEVENTH_SUS4 || Settings.baseLang.patterns.SEVENTH_SUS4 },
            get SEVENTH_a5(): string { return Language.CUSTOM.patterns.SEVENTH_a5 || Settings.baseLang.patterns.SEVENTH_a5 },
            get SEVENTH_a9(): string { return Language.CUSTOM.patterns.SEVENTH_a9 || Settings.baseLang.patterns.SEVENTH_a9 },
            get SEVENTH_b5(): string { return Language.CUSTOM.patterns.SEVENTH_b5 || Settings.baseLang.patterns.SEVENTH_b5 },
            get SEVENTH_b9(): string { return Language.CUSTOM.patterns.SEVENTH_b9 || Settings.baseLang.patterns.SEVENTH_b9 },
            get SIXTH(): string { return Language.CUSTOM.patterns.SIXTH || Settings.baseLang.patterns.SIXTH },
            get SIXTH_ADD9(): string { return Language.CUSTOM.patterns.SIXTH_ADD9 || Settings.baseLang.patterns.SIXTH_ADD9 },
            get SIXTH_MINOR(): string { return Language.CUSTOM.patterns.SIXTH_MINOR || Settings.baseLang.patterns.SIXTH_MINOR },
            get SIXTH_MINOR_ADD9(): string { return Language.CUSTOM.patterns.SIXTH_MINOR_ADD9 || Settings.baseLang.patterns.SIXTH_MINOR_ADD9 },
            get SIXTH_SUS4(): string { return Language.CUSTOM.patterns.SIXTH_SUS4 || Settings.baseLang.patterns.SIXTH_SUS4 },
            get THIRTEENTH_MAJ13(): string { return Language.CUSTOM.patterns.THIRTEENTH_MAJ13 || Settings.baseLang.patterns.THIRTEENTH_MAJ13 },
            get THIRTEENTH_MAJ13_a5(): string { return Language.CUSTOM.patterns.THIRTEENTH_MAJ13_a5 || Settings.baseLang.patterns.THIRTEENTH_MAJ13_a5 },
            get THIRTEENTH_MAJ13_a5a9(): string { return Language.CUSTOM.patterns.THIRTEENTH_MAJ13_a5a9 || Settings.baseLang.patterns.THIRTEENTH_MAJ13_a5a9 },
            get THIRTEENTH_b5a9(): string { return Language.CUSTOM.patterns.THIRTEENTH_b5a9 || Settings.baseLang.patterns.THIRTEENTH_b5a9 },
            get THIRTEENTH_MAJ13_a5b9(): string { return Language.CUSTOM.patterns.THIRTEENTH_MAJ13_a5b9 || Settings.baseLang.patterns.THIRTEENTH_MAJ13_a5b9},
            get THIRTEENTH_MAJ13_a9(): string { return Language.CUSTOM.patterns.THIRTEENTH_MAJ13_a9 || Settings.baseLang.patterns.THIRTEENTH_MAJ13_a9},
            get THIRTEENTH_MAJ13_b5(): string { return Language.CUSTOM.patterns.THIRTEENTH_MAJ13_b5 || Settings.baseLang.patterns.THIRTEENTH_MAJ13_b5},
            get THIRTEENTH_MAJ13_b5a9(): string { return Language.CUSTOM.patterns.THIRTEENTH_MAJ13_b5a9 || Settings.baseLang.patterns.THIRTEENTH_MAJ13_b5a9},
            get THIRTEENTH_MAJ13_b5b9(): string { return Language.CUSTOM.patterns.THIRTEENTH_MAJ13_b5b9 || Settings.baseLang.patterns.THIRTEENTH_MAJ13_b5b9},
            get THIRTEENTH_MAJ13_b9(): string { return Language.CUSTOM.patterns.THIRTEENTH_MAJ13_b9 || Settings.baseLang.patterns.THIRTEENTH_MAJ13_b9},
            get THIRTEENTH_MINOR(): string { return Language.CUSTOM.patterns.THIRTEENTH_MINOR || Settings.baseLang.patterns.THIRTEENTH_MINOR},
            get THIRTEENTH_MINOR_MAJ13(): string { return Language.CUSTOM.patterns.THIRTEENTH_MINOR_MAJ13 || Settings.baseLang.patterns.THIRTEENTH_MINOR_MAJ13},
            get THIRTEENTH_SUS4(): string { return Language.CUSTOM.patterns.THIRTEENTH_SUS4 || Settings.baseLang.patterns.THIRTEENTH_SUS4},
            get THIRTEENTH_a5(): string { return Language.CUSTOM.patterns.THIRTEENTH_a5 || Settings.baseLang.patterns.THIRTEENTH_a5},
            get THIRTEENTH_a5a9(): string { return Language.CUSTOM.patterns.THIRTEENTH_a5a9 || Settings.baseLang.patterns.THIRTEENTH_a5a9},
            get THIRTEENTH_a5b9(): string { return Language.CUSTOM.patterns.THIRTEENTH_a5b9 || Settings.baseLang.patterns.THIRTEENTH_a5b9},
            get THIRTEENTH_a9(): string { return Language.CUSTOM.patterns.THIRTEENTH_a9 || Settings.baseLang.patterns.THIRTEENTH_a9},
            get THIRTEENTH_b5(): string { return Language.CUSTOM.patterns.THIRTEENTH_b5 || Settings.baseLang.patterns.THIRTEENTH_b5},
            get THIRTEENTH_b5b9(): string { return Language.CUSTOM.patterns.THIRTEENTH_b5b9 || Settings.baseLang.patterns.THIRTEENTH_b5b9},
            get THIRTEENTH_b9(): string { return Language.CUSTOM.patterns.THIRTEENTH_b9 || Settings.baseLang.patterns.THIRTEENTH_b9},
        },
        shortPatterns: {
            get TRIAD_MAJOR(): string { return Language.CUSTOM.shortPatterns.TRIAD_MAJOR || Settings.baseLang.shortPatterns.TRIAD_MAJOR },
            get TRIAD_MINOR(): string { return Language.CUSTOM.shortPatterns.TRIAD_MINOR || Settings.baseLang.shortPatterns.TRIAD_MINOR },
            get TRIAD_AUGMENTED(): string { return Language.CUSTOM.shortPatterns.TRIAD_AUGMENTED || Settings.baseLang.shortPatterns.TRIAD_AUGMENTED },
            get TRIAD_DIMINISHED(): string { return Language.CUSTOM.shortPatterns.TRIAD_DIMINISHED || Settings.baseLang.shortPatterns.TRIAD_DIMINISHED },
            get TRIAD_SUS4(): string { return Language.CUSTOM.shortPatterns.TRIAD_SUS4 || Settings.baseLang.shortPatterns.TRIAD_SUS4 },
            get TRIAD_SUS2(): string { return Language.CUSTOM.shortPatterns.TRIAD_SUS2 || Settings.baseLang.shortPatterns.TRIAD_SUS2 },
            get TRIAD_QUARTAL(): string { return Language.CUSTOM.shortPatterns.TRIAD_QUARTAL || Settings.baseLang.shortPatterns.TRIAD_QUARTAL },
            get ELEVENTH(): string { return Language.CUSTOM.shortPatterns.ELEVENTH || Settings.baseLang.shortPatterns.ELEVENTH },
            get ELEVENTH_MAJ11(): string { return Language.CUSTOM.shortPatterns.ELEVENTH_MAJ11 || Settings.baseLang.shortPatterns.ELEVENTH_MAJ11 },
            get ELEVENTH_MINOR_MAJ11(): string { return Language.CUSTOM.shortPatterns.ELEVENTH_MINOR_MAJ11 || Settings.baseLang.shortPatterns.ELEVENTH_MINOR_MAJ11 },
            get ELEVENTH_a9(): string { return Language.CUSTOM.shortPatterns.ELEVENTH_a9 || Settings.baseLang.shortPatterns.ELEVENTH_a9 },
            get ELEVENTH_b9(): string { return Language.CUSTOM.shortPatterns.ELEVENTH_b9 || Settings.baseLang.shortPatterns.ELEVENTH_b9 },
            get NINTH(): string { return Language.CUSTOM.shortPatterns.NINTH || Settings.baseLang.shortPatterns.NINTH },
            get NINTH_ADD6(): string { return Language.CUSTOM.shortPatterns.NINTH_ADD6 || Settings.baseLang.shortPatterns.NINTH_ADD6 },
            get NINTH_MAJ9(): string { return Language.CUSTOM.shortPatterns.NINTH_MAJ9 || Settings.baseLang.shortPatterns.NINTH_MAJ9 },
            get NINTH_MAJ9_a11(): string { return Language.CUSTOM.shortPatterns.NINTH_MAJ9_a11 || Settings.baseLang.shortPatterns.NINTH_MAJ9_a11 },
            get NINTH_MINOR(): string { return Language.CUSTOM.shortPatterns.NINTH_MINOR || Settings.baseLang.shortPatterns.NINTH_MINOR },
            get NINTH_MINOR_MAJ9(): string { return Language.CUSTOM.shortPatterns.NINTH_MINOR_MAJ9 || Settings.baseLang.shortPatterns.NINTH_MINOR_MAJ9 },
            get NINTH_SUS4(): string { return Language.CUSTOM.shortPatterns.NINTH_SUS4 || Settings.baseLang.shortPatterns.NINTH_SUS4 },
            get NINTH_a11(): string { return Language.CUSTOM.shortPatterns.NINTH_a11 || Settings.baseLang.shortPatterns.NINTH_a11 },
            get NINTH_a5(): string { return Language.CUSTOM.shortPatterns.NINTH_a5 || Settings.baseLang.shortPatterns.NINTH_a5 },
            get NINTH_b5(): string { return Language.CUSTOM.shortPatterns.NINTH_b5 || Settings.baseLang.shortPatterns.NINTH_b5 },
            get POWER_CHORD(): string { return Language.CUSTOM.shortPatterns.POWER_CHORD || Settings.baseLang.shortPatterns.POWER_CHORD },
            get SEVENTH(): string { return Language.CUSTOM.shortPatterns.SEVENTH || Settings.baseLang.shortPatterns.SEVENTH },
            get SEVENTH_ADD11(): string { return Language.CUSTOM.shortPatterns.SEVENTH_ADD11 || Settings.baseLang.shortPatterns.SEVENTH_ADD11 },
            get SEVENTH_ADD13(): string { return Language.CUSTOM.shortPatterns.SEVENTH_ADD13 || Settings.baseLang.shortPatterns.SEVENTH_ADD13 },
            get SEVENTH_MAJ7(): string { return Language.CUSTOM.shortPatterns.SEVENTH_MAJ7 || Settings.baseLang.shortPatterns.SEVENTH_MAJ7 },
            get SEVENTH_MINOR(): string { return Language.CUSTOM.shortPatterns.SEVENTH_MINOR || Settings.baseLang.shortPatterns.SEVENTH_MINOR },
            get SEVENTH_MINOR_MAJ7(): string { return Language.CUSTOM.shortPatterns.SEVENTH_MINOR_MAJ7 || Settings.baseLang.shortPatterns.SEVENTH_MINOR_MAJ7 },
            get SEVENTH_MINOR_a5(): string { return Language.CUSTOM.shortPatterns.SEVENTH_MINOR_a5 || Settings.baseLang.shortPatterns.SEVENTH_MINOR_a5 },
            get SEVENTH_MINOR_b5(): string { return Language.CUSTOM.shortPatterns.SEVENTH_MINOR_b5 || Settings.baseLang.shortPatterns.SEVENTH_MINOR_b5 },
            get SEVENTH_MINOR_b9(): string { return Language.CUSTOM.shortPatterns.SEVENTH_MINOR_b9 || Settings.baseLang.shortPatterns.SEVENTH_MINOR_b9 },
            get SEVENTH_SUS4(): string { return Language.CUSTOM.shortPatterns.SEVENTH_SUS4 || Settings.baseLang.shortPatterns.SEVENTH_SUS4 },
            get SEVENTH_a5(): string { return Language.CUSTOM.shortPatterns.SEVENTH_a5 || Settings.baseLang.shortPatterns.SEVENTH_a5 },
            get SEVENTH_a9(): string { return Language.CUSTOM.shortPatterns.SEVENTH_a9 || Settings.baseLang.shortPatterns.SEVENTH_a9 },
            get SEVENTH_b5(): string { return Language.CUSTOM.shortPatterns.SEVENTH_b5 || Settings.baseLang.shortPatterns.SEVENTH_b5 },
            get SEVENTH_b9(): string { return Language.CUSTOM.shortPatterns.SEVENTH_b9 || Settings.baseLang.shortPatterns.SEVENTH_b9 },
            get SIXTH(): string { return Language.CUSTOM.shortPatterns.SIXTH || Settings.baseLang.shortPatterns.SIXTH },
            get SIXTH_ADD9(): string { return Language.CUSTOM.shortPatterns.SIXTH_ADD9 || Settings.baseLang.shortPatterns.SIXTH_ADD9 },
            get SIXTH_MINOR(): string { return Language.CUSTOM.shortPatterns.SIXTH_MINOR || Settings.baseLang.shortPatterns.SIXTH_MINOR },
            get SIXTH_MINOR_ADD9(): string { return Language.CUSTOM.shortPatterns.SIXTH_MINOR_ADD9 || Settings.baseLang.shortPatterns.SIXTH_MINOR_ADD9 },
            get SIXTH_SUS4(): string { return Language.CUSTOM.shortPatterns.SIXTH_SUS4 || Settings.baseLang.shortPatterns.SIXTH_SUS4 },
            get THIRTEENTH_MAJ13(): string { return Language.CUSTOM.shortPatterns.THIRTEENTH_MAJ13 || Settings.baseLang.shortPatterns.THIRTEENTH_MAJ13 },
            get THIRTEENTH_MAJ13_a5(): string { return Language.CUSTOM.shortPatterns.THIRTEENTH_MAJ13_a5 || Settings.baseLang.shortPatterns.THIRTEENTH_MAJ13_a5 },
            get THIRTEENTH_MAJ13_a5a9(): string { return Language.CUSTOM.shortPatterns.THIRTEENTH_MAJ13_a5a9 || Settings.baseLang.shortPatterns.THIRTEENTH_MAJ13_a5a9 },
            get THIRTEENTH_b5a9(): string { return Language.CUSTOM.shortPatterns.THIRTEENTH_b5a9 || Settings.baseLang.shortPatterns.THIRTEENTH_b5a9 },
            get THIRTEENTH_MAJ13_a5b9(): string { return Language.CUSTOM.shortPatterns.THIRTEENTH_MAJ13_a5b9 || Settings.baseLang.shortPatterns.THIRTEENTH_MAJ13_a5b9},
            get THIRTEENTH_MAJ13_a9(): string { return Language.CUSTOM.shortPatterns.THIRTEENTH_MAJ13_a9 || Settings.baseLang.shortPatterns.THIRTEENTH_MAJ13_a9},
            get THIRTEENTH_MAJ13_b5(): string { return Language.CUSTOM.shortPatterns.THIRTEENTH_MAJ13_b5 || Settings.baseLang.shortPatterns.THIRTEENTH_MAJ13_b5},
            get THIRTEENTH_MAJ13_b5a9(): string { return Language.CUSTOM.shortPatterns.THIRTEENTH_MAJ13_b5a9 || Settings.baseLang.shortPatterns.THIRTEENTH_MAJ13_b5a9},
            get THIRTEENTH_MAJ13_b5b9(): string { return Language.CUSTOM.shortPatterns.THIRTEENTH_MAJ13_b5b9 || Settings.baseLang.shortPatterns.THIRTEENTH_MAJ13_b5b9},
            get THIRTEENTH_MAJ13_b9(): string { return Language.CUSTOM.shortPatterns.THIRTEENTH_MAJ13_b9 || Settings.baseLang.shortPatterns.THIRTEENTH_MAJ13_b9},
            get THIRTEENTH_MINOR(): string { return Language.CUSTOM.shortPatterns.THIRTEENTH_MINOR || Settings.baseLang.shortPatterns.THIRTEENTH_MINOR},
            get THIRTEENTH_MINOR_MAJ13(): string { return Language.CUSTOM.shortPatterns.THIRTEENTH_MINOR_MAJ13 || Settings.baseLang.shortPatterns.THIRTEENTH_MINOR_MAJ13},
            get THIRTEENTH_SUS4(): string { return Language.CUSTOM.shortPatterns.THIRTEENTH_SUS4 || Settings.baseLang.shortPatterns.THIRTEENTH_SUS4},
            get THIRTEENTH_a5(): string { return Language.CUSTOM.shortPatterns.THIRTEENTH_a5 || Settings.baseLang.shortPatterns.THIRTEENTH_a5},
            get THIRTEENTH_a5a9(): string { return Language.CUSTOM.shortPatterns.THIRTEENTH_a5a9 || Settings.baseLang.shortPatterns.THIRTEENTH_a5a9},
            get THIRTEENTH_a5b9(): string { return Language.CUSTOM.shortPatterns.THIRTEENTH_a5b9 || Settings.baseLang.shortPatterns.THIRTEENTH_a5b9},
            get THIRTEENTH_a9(): string { return Language.CUSTOM.shortPatterns.THIRTEENTH_a9 || Settings.baseLang.shortPatterns.THIRTEENTH_a9},
            get THIRTEENTH_b5(): string { return Language.CUSTOM.shortPatterns.THIRTEENTH_b5 || Settings.baseLang.shortPatterns.THIRTEENTH_b5},
            get THIRTEENTH_b5b9(): string { return Language.CUSTOM.shortPatterns.THIRTEENTH_b5b9 || Settings.baseLang.shortPatterns.THIRTEENTH_b5b9},
            get THIRTEENTH_b9(): string { return Language.CUSTOM.shortPatterns.THIRTEENTH_b9 || Settings.baseLang.shortPatterns.THIRTEENTH_b9},
        },
        temperaments: {
            get ET12(): string { return Language.CUSTOM.temperaments.ET12 || Settings.baseLang.temperaments.ET12 },
            get LIMIT_5_SYMMETRIC_N1(): string { return Language.CUSTOM.temperaments.LIMIT_5_SYMMETRIC_N1 || Settings.baseLang.temperaments.LIMIT_5_SYMMETRIC_N1 },
            get LIMIT_5_SYMMETRIC_N2(): string { return Language.CUSTOM.temperaments.LIMIT_5_SYMMETRIC_N2 || Settings.baseLang.temperaments.LIMIT_5_SYMMETRIC_N2 },
            get PYTHAGOREAN(): string { return Language.CUSTOM.temperaments.PYTHAGOREAN || Settings.baseLang.temperaments.PYTHAGOREAN },
        },
        words: {
            get note(): string { return Language.CUSTOM.words.note || Settings.baseLang.words.note },
            get chord(): string { return Language.CUSTOM.words.chord || Settings.baseLang.words.chord },
            get scale(): string { return Language.CUSTOM.words.scale || Settings.baseLang.words.scale },
            get tonality(): string { return Language.CUSTOM.words.tonality || Settings.baseLang.words.tonality },
            get tuning(): string { return Language.CUSTOM.words.tuning || Settings.baseLang.words.tuning },
            get temperament(): string { return Language.CUSTOM.words.temperament || Settings.baseLang.words.temperament },
            get degreeFunction(): string { return Language.CUSTOM.words.degreeFunction || Settings.baseLang.words.degreeFunction },
            get degree(): string { return Language.CUSTOM.words.degree || Settings.baseLang.words.degree },
            get pitch(): string { return Language.CUSTOM.words.pitch || Settings.baseLang.words.pitch },
            get pattern(): string { return Language.CUSTOM.words.pattern || Settings.baseLang.words.pattern },
            get inversion(): string { return Language.CUSTOM.words.inversion || Settings.baseLang.words.inversion },
            get root(): string { return Language.CUSTOM.words.root || Settings.baseLang.words.root },
            get diatonicAlt(): string { return Language.CUSTOM.words.diatonicAlt || Settings.baseLang.words.diatonicAlt },
            get diatonic(): string { return Language.CUSTOM.words.diatonic || Settings.baseLang.words.diatonic },
            get chromatic(): string { return Language.CUSTOM.words.chromatic || Settings.baseLang.words.chromatic },
        },
        quality: {
            get perfect(): string { return Language.CUSTOM.quality.perfect || Settings.baseLang.quality.perfect },
            get major(): string { return Language.CUSTOM.quality.major || Settings.baseLang.quality.major },
            get minor(): string { return Language.CUSTOM.quality.minor || Settings.baseLang.quality.minor },
            get diminished(): string { return Language.CUSTOM.quality.diminished || Settings.baseLang.quality.diminished },
            get augmented(): string { return Language.CUSTOM.quality.augmented || Settings.baseLang.quality.augmented },
            get doublyDiminished(): string { return Language.CUSTOM.quality.doublyDiminished || Settings.baseLang.quality.doublyDiminished },
            get doublyAugmented(): string { return Language.CUSTOM.quality.doublyAugmented || Settings.baseLang.quality.doublyAugmented },
        }
    },
    scales: {
        get MAJOR(): string { return Settings.lang.scales.MAJOR },
        get MINOR(): string { return Settings.lang.scales.MINOR },
        get DORIAN(): string { return Settings.lang.scales.DORIAN },
        get PHRYGIAN(): string { return Settings.lang.scales.PHRYGIAN },
        get LYDIAN(): string { return Settings.lang.scales.LYDIAN },
        get MIXOLYDIAN(): string { return Settings.lang.scales.MIXOLYDIAN },
        get LOCRIAN(): string { return Settings.lang.scales.LOCRIAN },
        get HARMONIC_MINOR(): string { return Settings.lang.scales.HARMONIC_MINOR },
        get LOCRIAN_a6(): string { return Settings.lang.scales.LOCRIAN_a6 },
        get IONIAN_a5(): string { return Settings.lang.scales.IONIAN_a5 },
        get DORIAN_a4(): string { return Settings.lang.scales.DORIAN_a4 },
        get MIXOLYDIAN_b9_b13(): string { return Settings.lang.scales.MIXOLYDIAN_b9_b13 },
        get LYDIAN_a2(): string { return Settings.lang.scales.LYDIAN_a2 },
        get SUPERLOCRIAN_bb7(): string { return Settings.lang.scales.SUPERLOCRIAN_bb7 },
        get HARMONIC_MAJOR(): string { return Settings.lang.scales.HARMONIC_MAJOR },
        get DORIAN_b5(): string { return Settings.lang.scales.DORIAN_b5 },
        get PHRYGIAN_b4(): string { return Settings.lang.scales.PHRYGIAN_b4 },
        get LYDIAN_b3(): string { return Settings.lang.scales.LYDIAN_b3 },
        get MIXOLYDIAN_b2(): string { return Settings.lang.scales.MIXOLYDIAN_b2 },
        get AEOLIAN_b1(): string { return Settings.lang.scales.AEOLIAN_b1 },
        get LOCRIAN_bb7(): string { return Settings.lang.scales.LOCRIAN_bb7 },
        get MELODIC_MINOR(): string { return Settings.lang.scales.MELODIC_MINOR },
        get DORIAN_b2(): string { return Settings.lang.scales.DORIAN_b2 },
        get LYDIAN_a5(): string { return Settings.lang.scales.LYDIAN_a5 },
        get LYDIAN_b7(): string { return Settings.lang.scales.LYDIAN_b7 },
        get MIXOLYDIAN_b13(): string { return Settings.lang.scales.MIXOLYDIAN_b13 },
        get LOCRIAN_a2(): string { return Settings.lang.scales.LOCRIAN_a2 },
        get SUPERLOCRIAN(): string { return Settings.lang.scales.SUPERLOCRIAN },
        get DOUBLE_HARMONIC(): string { return Settings.lang.scales.DOUBLE_HARMONIC },
        get LYDIAN_a2_a6(): string { return Settings.lang.scales.LYDIAN_a2_a6 },
        get ULTRAPHRYGIAN(): string { return Settings.lang.scales.ULTRAPHRYGIAN },
        get HUNGARIAN_MINOR(): string { return Settings.lang.scales.HUNGARIAN_MINOR },
        get ORIENTAL(): string { return Settings.lang.scales.ORIENTAL },
        get IONIAN_AUGMENTED_a2(): string { return Settings.lang.scales.IONIAN_AUGMENTED_a2 },
        get LOCRIAN_bb3_bb7(): string { return Settings.lang.scales.LOCRIAN_bb3_bb7 },
        get NEAPOLITAN_MINOR(): string { return Settings.lang.scales.NEAPOLITAN_MINOR },
        get NEAPOLITAN_MAJOR(): string { return Settings.lang.scales.NEAPOLITAN_MAJOR },
        get BLUES_b5(): string { return Settings.lang.scales.BLUES_b5 },
        get BLUES_a4(): string { return Settings.lang.scales.BLUES_a4 },
        get WHOLE_TONE(): string { return Settings.lang.scales.WHOLE_TONE },
        get PENTATONIC_MINOR(): string { return Settings.lang.scales.PENTATONIC_MINOR },
        get PENTATONIC(): string { return Settings.lang.scales.PENTATONIC },
        get EGYPCIAN(): string { return Settings.lang.scales.EGYPCIAN },
        get BLUES_MINOR(): string { return Settings.lang.scales.BLUES_MINOR },
        get BLUES_MAJOR(): string { return Settings.lang.scales.BLUES_MAJOR },
        get CHROMATIC(): string { return Settings.lang.scales.CHROMATIC },
        get AUGMENTED_TRIAD(): string { return Settings.lang.scales.AUGMENTED_TRIAD },
        get DIMINISHED_7th(): string { return Settings.lang.scales.DIMINISHED_7th },
        get MESSIAEN_V_TRUNCATED(): string { return Settings.lang.scales.MESSIAEN_V_TRUNCATED },
        get DOM7b5(): string { return Settings.lang.scales.DOM7b5 },
        get MESSIAEN_INV_III_V_TRUNCATED_n2(): string { return Settings.lang.scales.MESSIAEN_INV_III_V_TRUNCATED_n2 },
        get HALF_DIMINISHED(): string { return Settings.lang.scales.HALF_DIMINISHED },
        get MESSIAEN_V(): string { return Settings.lang.scales.MESSIAEN_V },
        get RAGA_INDRUPRIYA_INDIA(): string { return Settings.lang.scales.RAGA_INDRUPRIYA_INDIA },
        get MESSIAEN_II_TRUNCATED_n3(): string { return Settings.lang.scales.MESSIAEN_II_TRUNCATED_n3 },
        get MESSIAEN_III_INV(): string { return Settings.lang.scales.MESSIAEN_III_INV },
        get MESSIAEN_IV(): string { return Settings.lang.scales.MESSIAEN_IV },
        get MESSIAEN_VI(): string { return Settings.lang.scales.MESSIAEN_VI },
        get MESSIAEN_VII(): string { return Settings.lang.scales.MESSIAEN_VII },
        get BEBOP_MAJOR(): string { return Settings.lang.scales.BEBOP_MAJOR },
    },
    symbols: {
        sharp: "♯",
        bemol: "♭",
        alts: function (n: number): string {
            if (n < 0)
                return Settings.symbols.bemol.repeat(-n);
            else if (n > 0)
                return Settings.symbols.sharp.repeat(n);
            else
                return "";
        }
    },
    mods: {
        get b9(): string { return Settings.symbols.alts(-1) + "9"; },
        get a9(): string { return Settings.symbols.alts(1) + "9"; },
        get b5(): string { return Settings.symbols.alts(-1) + "5"; },
        get a5(): string { return Settings.symbols.alts(1) + "5"; },
        get a11(): string { return Settings.symbols.alts(1) + "11"; },
        get add(): string { return "ADD"; }
    },
    patterns: {
        get TRIAD_MAJOR(): string { return Settings.lang.patterns.TRIAD_MAJOR },
        get TRIAD_MINOR(): string { return Settings.lang.patterns.TRIAD_MINOR },
        get TRIAD_AUGMENTED(): string { return Settings.lang.patterns.TRIAD_AUGMENTED },
        get TRIAD_DIMINISHED(): string { return Settings.lang.patterns.TRIAD_DIMINISHED },
        get TRIAD_SUS4(): string { return Settings.lang.patterns.TRIAD_SUS4 },
        get TRIAD_SUS2(): string { return Settings.lang.patterns.TRIAD_SUS2 },
        get TRIAD_QUARTAL(): string { return Settings.lang.patterns.TRIAD_QUARTAL },
        get ELEVENTH(): string { return Settings.lang.patterns.ELEVENTH },
        get ELEVENTH_MAJ11(): string { return Settings.lang.patterns.ELEVENTH_MAJ11 },
        get ELEVENTH_MINOR_MAJ11(): string { return Settings.lang.patterns.ELEVENTH_MINOR_MAJ11 },
        get ELEVENTH_a9(): string { return Settings.lang.patterns.ELEVENTH_a9 },
        get ELEVENTH_b9(): string { return Settings.lang.patterns.ELEVENTH_b9 },
        get NINTH(): string { return Settings.lang.patterns.NINTH },
        get NINTH_ADD6(): string { return Settings.lang.patterns.NINTH_ADD6 },
        get NINTH_MAJ9(): string { return Settings.lang.patterns.NINTH_MAJ9 },
        get NINTH_MAJ9_a11(): string { return Settings.lang.patterns.NINTH_MAJ9_a11 },
        get NINTH_MINOR(): string { return Settings.lang.patterns.NINTH_MINOR },
        get NINTH_MINOR_MAJ9(): string { return Settings.lang.patterns.NINTH_MINOR_MAJ9 },
        get NINTH_SUS4(): string { return Settings.lang.patterns.NINTH_SUS4 },
        get NINTH_a11(): string { return Settings.lang.patterns.NINTH_a11 },
        get NINTH_a5(): string { return Settings.lang.patterns.NINTH_a5 },
        get NINTH_b5(): string { return Settings.lang.patterns.NINTH_b5 },
        get POWER_CHORD(): string { return Settings.lang.patterns.POWER_CHORD },
        get SEVENTH(): string { return Settings.lang.patterns.SEVENTH },
        get SEVENTH_ADD11(): string { return Settings.lang.patterns.SEVENTH_ADD11 },
        get SEVENTH_ADD13(): string { return Settings.lang.patterns.SEVENTH_ADD13 },
        get SEVENTH_MAJ7(): string { return Settings.lang.patterns.SEVENTH_MAJ7 },
        get SEVENTH_MINOR(): string { return Settings.lang.patterns.SEVENTH_MINOR },
        get SEVENTH_MINOR_MAJ7(): string { return Settings.lang.patterns.SEVENTH_MINOR_MAJ7 },
        get SEVENTH_MINOR_a5(): string { return Settings.lang.patterns.SEVENTH_MINOR_a5 },
        get SEVENTH_MINOR_b5(): string { return Settings.lang.patterns.SEVENTH_MINOR_b5 },
        get SEVENTH_MINOR_b9(): string { return Settings.lang.patterns.SEVENTH_MINOR_b9 },
        get SEVENTH_SUS4(): string { return Settings.lang.patterns.SEVENTH_SUS4 },
        get SEVENTH_a5(): string { return Settings.lang.patterns.SEVENTH_a5 },
        get SEVENTH_a9(): string { return Settings.lang.patterns.SEVENTH_a9 },
        get SEVENTH_b5(): string { return Settings.lang.patterns.SEVENTH_b5 },
        get SEVENTH_b9(): string { return Settings.lang.patterns.SEVENTH_b9 },
        get SIXTH(): string { return Settings.lang.patterns.SIXTH },
        get SIXTH_ADD9(): string { return Settings.lang.patterns.SIXTH_ADD9 },
        get SIXTH_MINOR(): string { return Settings.lang.patterns.SIXTH_MINOR },
        get SIXTH_MINOR_ADD9(): string { return Settings.lang.patterns.SIXTH_MINOR_ADD9 },
        get SIXTH_SUS4(): string { return Settings.lang.patterns.SIXTH_SUS4 },
        get THIRTEENTH_MAJ13(): string { return Settings.lang.patterns.THIRTEENTH_MAJ13 },
        get THIRTEENTH_MAJ13_a5(): string { return Settings.lang.patterns.THIRTEENTH_MAJ13_a5 },
        get THIRTEENTH_MAJ13_a5a9(): string { return Settings.lang.patterns.THIRTEENTH_MAJ13_a5a9 },
        get THIRTEENTH_b5a9(): string { return Settings.lang.patterns.THIRTEENTH_b5a9 },
        get THIRTEENTH_MAJ13_a5b9(): string { return Settings.lang.patterns.THIRTEENTH_MAJ13_a5b9 },
        get THIRTEENTH_MAJ13_a9(): string { return Settings.lang.patterns.THIRTEENTH_MAJ13_a9 },
        get THIRTEENTH_MAJ13_b5(): string { return Settings.lang.patterns.THIRTEENTH_MAJ13_b5 },
        get THIRTEENTH_MAJ13_b5a9(): string { return Settings.lang.patterns.THIRTEENTH_MAJ13_b5a9 },
        get THIRTEENTH_MAJ13_b5b9(): string { return Settings.lang.patterns.THIRTEENTH_MAJ13_b5b9 },
        get THIRTEENTH_MAJ13_b9(): string { return Settings.lang.patterns.THIRTEENTH_MAJ13_b9 },
        get THIRTEENTH_MINOR(): string { return Settings.lang.patterns.THIRTEENTH_MINOR },
        get THIRTEENTH_MINOR_MAJ13(): string { return Settings.lang.patterns.THIRTEENTH_MINOR_MAJ13 },
        get THIRTEENTH_SUS4(): string { return Settings.lang.patterns.THIRTEENTH_SUS4 },
        get THIRTEENTH_a5(): string { return Settings.lang.patterns.THIRTEENTH_a5 },
        get THIRTEENTH_a5a9(): string { return Settings.lang.patterns.THIRTEENTH_a5a9 },
        get THIRTEENTH_a5b9(): string { return Settings.lang.patterns.THIRTEENTH_a5b9 },
        get THIRTEENTH_a9(): string { return Settings.lang.patterns.THIRTEENTH_a9 },
        get THIRTEENTH_b5(): string { return Settings.lang.patterns.THIRTEENTH_b5 },
        get THIRTEENTH_b5b9(): string { return Settings.lang.patterns.THIRTEENTH_b5b9 },
        get THIRTEENTH_b9(): string { return Settings.lang.patterns.THIRTEENTH_b9 }
    },
    shortPatterns: {
        get TRIAD_MAJOR(): string { return Settings.lang.shortPatterns.TRIAD_MAJOR },
        get TRIAD_MINOR(): string { return Settings.lang.shortPatterns.TRIAD_MINOR },
        get TRIAD_AUGMENTED(): string { return Settings.lang.shortPatterns.TRIAD_AUGMENTED },
        get TRIAD_DIMINISHED(): string { return Settings.lang.shortPatterns.TRIAD_DIMINISHED },
        get TRIAD_SUS4(): string { return Settings.lang.shortPatterns.TRIAD_SUS4 },
        get TRIAD_SUS2(): string { return Settings.lang.shortPatterns.TRIAD_SUS2 },
        get TRIAD_QUARTAL(): string { return Settings.lang.shortPatterns.TRIAD_QUARTAL },
        get ELEVENTH(): string { return Settings.lang.shortPatterns.ELEVENTH },
        get ELEVENTH_MAJ11(): string { return Settings.lang.shortPatterns.ELEVENTH_MAJ11 },
        get ELEVENTH_MINOR_MAJ11(): string { return Settings.lang.shortPatterns.ELEVENTH_MINOR_MAJ11 },
        get ELEVENTH_a9(): string { return Settings.lang.shortPatterns.ELEVENTH_a9 },
        get ELEVENTH_b9(): string { return Settings.lang.shortPatterns.ELEVENTH_b9 },
        get NINTH(): string { return Settings.lang.shortPatterns.NINTH },
        get NINTH_ADD6(): string { return Settings.lang.shortPatterns.NINTH_ADD6 },
        get NINTH_MAJ9(): string { return Settings.lang.shortPatterns.NINTH_MAJ9 },
        get NINTH_MAJ9_a11(): string { return Settings.lang.shortPatterns.NINTH_MAJ9_a11 },
        get NINTH_MINOR(): string { return Settings.lang.shortPatterns.NINTH_MINOR },
        get NINTH_MINOR_MAJ9(): string { return Settings.lang.shortPatterns.NINTH_MINOR_MAJ9 },
        get NINTH_SUS4(): string { return Settings.lang.shortPatterns.NINTH_SUS4 },
        get NINTH_a11(): string { return Settings.lang.shortPatterns.NINTH_a11 },
        get NINTH_a5(): string { return Settings.lang.shortPatterns.NINTH_a5 },
        get NINTH_b5(): string { return Settings.lang.shortPatterns.NINTH_b5 },
        get POWER_CHORD(): string { return Settings.lang.shortPatterns.POWER_CHORD },
        get SEVENTH(): string { return Settings.lang.shortPatterns.SEVENTH },
        get SEVENTH_ADD11(): string { return Settings.lang.shortPatterns.SEVENTH_ADD11 },
        get SEVENTH_ADD13(): string { return Settings.lang.shortPatterns.SEVENTH_ADD13 },
        get SEVENTH_MAJ7(): string { return Settings.lang.shortPatterns.SEVENTH_MAJ7 },
        get SEVENTH_MINOR(): string { return Settings.lang.shortPatterns.SEVENTH_MINOR },
        get SEVENTH_MINOR_MAJ7(): string { return Settings.lang.shortPatterns.SEVENTH_MINOR_MAJ7 },
        get SEVENTH_MINOR_a5(): string { return Settings.lang.shortPatterns.SEVENTH_MINOR_a5 },
        get SEVENTH_MINOR_b5(): string { return Settings.lang.shortPatterns.SEVENTH_MINOR_b5 },
        get SEVENTH_MINOR_b9(): string { return Settings.lang.shortPatterns.SEVENTH_MINOR_b9 },
        get SEVENTH_SUS4(): string { return Settings.lang.shortPatterns.SEVENTH_SUS4 },
        get SEVENTH_a5(): string { return Settings.lang.shortPatterns.SEVENTH_a5 },
        get SEVENTH_a9(): string { return Settings.lang.shortPatterns.SEVENTH_a9 },
        get SEVENTH_b5(): string { return Settings.lang.shortPatterns.SEVENTH_b5 },
        get SEVENTH_b9(): string { return Settings.lang.shortPatterns.SEVENTH_b9 },
        get SIXTH(): string { return Settings.lang.shortPatterns.SIXTH },
        get SIXTH_ADD9(): string { return Settings.lang.shortPatterns.SIXTH_ADD9 },
        get SIXTH_MINOR(): string { return Settings.lang.shortPatterns.SIXTH_MINOR },
        get SIXTH_MINOR_ADD9(): string { return Settings.lang.shortPatterns.SIXTH_MINOR_ADD9 },
        get SIXTH_SUS4(): string { return Settings.lang.shortPatterns.SIXTH_SUS4 },
        get THIRTEENTH_MAJ13(): string { return Settings.lang.shortPatterns.THIRTEENTH_MAJ13 },
        get THIRTEENTH_MAJ13_a5(): string { return Settings.lang.shortPatterns.THIRTEENTH_MAJ13_a5 },
        get THIRTEENTH_MAJ13_a5a9(): string { return Settings.lang.shortPatterns.THIRTEENTH_MAJ13_a5a9 },
        get THIRTEENTH_b5a9(): string { return Settings.lang.shortPatterns.THIRTEENTH_b5a9 },
        get THIRTEENTH_MAJ13_a5b9(): string { return Settings.lang.shortPatterns.THIRTEENTH_MAJ13_a5b9 },
        get THIRTEENTH_MAJ13_a9(): string { return Settings.lang.shortPatterns.THIRTEENTH_MAJ13_a9 },
        get THIRTEENTH_MAJ13_b5(): string { return Settings.lang.shortPatterns.THIRTEENTH_MAJ13_b5 },
        get THIRTEENTH_MAJ13_b5a9(): string { return Settings.lang.shortPatterns.THIRTEENTH_MAJ13_b5a9 },
        get THIRTEENTH_MAJ13_b5b9(): string { return Settings.lang.shortPatterns.THIRTEENTH_MAJ13_b5b9 },
        get THIRTEENTH_MAJ13_b9(): string { return Settings.lang.shortPatterns.THIRTEENTH_MAJ13_b9 },
        get THIRTEENTH_MINOR(): string { return Settings.lang.shortPatterns.THIRTEENTH_MINOR },
        get THIRTEENTH_MINOR_MAJ13(): string { return Settings.lang.shortPatterns.THIRTEENTH_MINOR_MAJ13 },
        get THIRTEENTH_SUS4(): string { return Settings.lang.shortPatterns.THIRTEENTH_SUS4 },
        get THIRTEENTH_a5(): string { return Settings.lang.shortPatterns.THIRTEENTH_a5 },
        get THIRTEENTH_a5a9(): string { return Settings.lang.shortPatterns.THIRTEENTH_a5a9 },
        get THIRTEENTH_a5b9(): string { return Settings.lang.shortPatterns.THIRTEENTH_a5b9 },
        get THIRTEENTH_a9(): string { return Settings.lang.shortPatterns.THIRTEENTH_a9 },
        get THIRTEENTH_b5(): string { return Settings.lang.shortPatterns.THIRTEENTH_b5 },
        get THIRTEENTH_b5b9(): string { return Settings.lang.shortPatterns.THIRTEENTH_b5b9 },
        get THIRTEENTH_b9(): string { return Settings.lang.shortPatterns.THIRTEENTH_b9 }
    }
}